name: CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: devsecops-demo

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Log in to GitHub Container Registry
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Set up metadata for Docker image
      - name: Docker metadata
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}

      # Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ github.repository }}:main
            ${{ env.REGISTRY }}/${{ github.repository }}:sha-${{ github.sha }}

      # Run Trivy scan
      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.REGISTRY }}/${{ github.repository }}:sha-${{ github.sha }}

  update-deployment:
    name: Update Kubernetes Deployment
    runs-on: ubuntu-latest
    needs: build-and-push
    env:
      REGISTRY: ghcr.io
      IMAGE_TAG: ${{ github.sha }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Pull latest main to avoid conflicts
        run: |
          git fetch origin main
          git reset --hard origin/main

      - name: Update deployment image
        run: |
          NEW_IMAGE="${REGISTRY}/${GITHUB_REPOSITORY,,}:sha-${IMAGE_TAG}"
          sed -i "s|image: ${REGISTRY}/.*|image: ${NEW_IMAGE}|g" kubernetes/deployment.yaml
          echo "Updated deployment to use image: ${NEW_IMAGE}"
          grep -A 1 "image:" kubernetes/deployment.yaml

      - name: Commit and push deployment changes
        run: |
          git add kubernetes/deployment.yaml
          git commit -m "Update deployment image to ${NEW_IMAGE}" || echo "No changes to commit"
          git push origin main
